n = int(input('Digite um número e saiba sua tabuada:'))
a = n*1
b = n*2
c = n*3
d = n*4
e = n*5
f = n*6
g = n*7
i = n*8
j = n*9
k = n*10
print('='*30)
print('Tabuada do {} \n '.format(n),
      '\n 1x{}'.format(n), '= {}'.format(a),
      '\n 2x{}'.format(n), '= {}'.format(b),
      '\n 3x{}'.format(n), '= {}'.format(c),
      '\n 4x{}'.format(n), '= {}'.format(d),
      '\n 5x{}'.format(n), '= {}'.format(e),
      '\n 6x{}'.format(n), '= {}'.format(f),
      '\n 7x{}'.format(n), '= {}'.format(g),
      '\n 8x{}'.format(n), '= {}'.format(i),
      '\n 9x{}'.format(n), '= {}'.format(j),
      '\n 10x{}'.format(n), '= {}'.format(k))
print('='*30)